# 1. Define the common settings using an Anchor (&)
common_settings: &common
  managed: true
  username: cisco
  password: cisco
  provide_url_agg01: "https://192.168.1.87"
  provide_url_agg02: "https://192.168.1.190"


  vrfs:
    "xx01-xx-core":
      description: "VRF for xx01-xx-core"
    "xx02-xx-core":
      description: "VRF for xx02-xx-core"
    "xx03-xx-core":
      description: "VRF for xx03-xx-core"
    "xx06-xx-core":
      description: "VRF for xx06-xx-core"
    "vpc":
      description: "VRF for vpc"





      
#######################################################################
##### The below config applies the variables above to the switches#####
                        #######################
                        #####DO NOT CHANGE#####
                        #######################
#######################################################################

# 2. Reference the common settings using an Alias (*)
twe-agg01:
  <<: *common                # This "pulls in" everything from common_settings
  name: "twe-agg01"
  url: "https://192.168.1.87"

twe-agg02:
  <<: *common                # Same here
  name: "twe-agg02"
  url: "https://192.168.1.190"
